name: Build and commit to main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: main build
        run:
        |
          docker build . --file Dockerfile --tag example
          docker container create --name main_build example:latest
          docker cp main_build:/opt/cccedict2json/output ./output
      - name: build and commit to main
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          GITHUB_TOKEN: $
          BRANCH: main
          FOLDER: output
          CLEAN: false
